<?php

namespace SerieBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ActorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActorRepository extends EntityRepository
{
  /**
   * @param $value
   * @return array
   */
  public function getBySearchValue($value) {
    $qb = $this->createQueryBuilder('a');

    $qb
        ->where($qb->expr()->like('a.firstname', '?1'))
        ->orWhere($qb->expr()->like('a.lastname', '?1'))
        ->setParameter(1, '%' . $value . '%');
    $query = $qb->getQuery();


    return $query->getResult();
  }

  public function getAllActorsByLastname($nbResult = 30, $nbPage = 0) {
    $qb = $this->createQueryBuilder('a');

    $qb
        ->orderBy('a.lastname' ,'ASC')
        ->setFirstResult($nbPage * $nbResult)
        ->setMaxResults($nbResult);
    $query = $qb->getQuery();


    return $query->getResult();

  }

}
