<?php

namespace ToolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LikeDislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeDislikeRepository extends EntityRepository
{
  public function findTest() {
    // http://stackoverflow.com/questions/6637506/doing-a-where-in-subquery-in-doctrine-2
    $qb = $this->createQueryBuilder('ld');

    // chaque série avec leur note moyenne
//    $qb
//        ->select('s.name')
//        ->addSelect($qb->expr()->avg('e.score').' AS moyenne')
//        ->from('ToolBundle\Entity\Evaluate', 'e')
//        // TODO: ajouter la jointure
//        ->groupBy('e.serie')
//        ->orderBy('moyenne' ,'DESC');
//    $query = $qb->getQuery();

    $qb
        ->select('c.id')
        ->addSelect($qb->expr()->count('ld.id').' AS nbLike')
        ->innerJoin('ld.comment', 'c')
        ->where('ld.likeIt = true')
        ->groupBy('c.id')
        ->orderBy('nbLike' ,'DESC');
    $query = $qb->getQuery();

    return $query->getResult();
  }

  public function checkValid($userId, $commentId) {
    $qb = $this->createQueryBuilder('ld');
    $qb
        ->where('ld.user = :user')
        ->andWhere('ld.comment = :serie')
        ->setParameter('user', $userId)
        ->setParameter('serie', $commentId);
    $query = $qb->getQuery();

    return $query->getOneOrNullResult();
  }
}
