<?php

namespace ToolBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LikeDislikeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikeDislikeRepository extends EntityRepository
{
}
