serie_homepage:
    path:     /
    defaults: { _controller: SerieBundle:Default:index }

serie_top10:
    path:     /top10
    defaults: { _controller: SerieBundle:Default:top10 }

serie_del:
    path:     /del/{id}
    defaults: { _controller: SerieBundle:Default:del }
    requirements:
        id:  "\d+"

serie_detail:
    path:     /detail/{id}
    defaults: { _controller: SerieBundle:Default:detail }
    requirements:
        id:  "\d+"

serie_list:
    path:     /list/
    defaults: { _controller: SerieBundle:Default:list }

serie_add:
    path:     /add
    defaults: { _controller: SerieBundle:Default:add }