serie_homepage:
    path:     /
    defaults: { _controller: SerieBundle:Default:index }

serie_top10:
    path:     /top10
    defaults: { _controller: SerieBundle:Default:top10 }

serie_add:
    path:     /add
    defaults: { _controller: SerieBundle:Default:add }

serie_del:
    path:     /del/{id}
    defaults: { _controller: SerieBundle:Default:del }
    requirements:
        id:  "\d+"

serie_mod:
    path:     /mod/{id}
    defaults: { _controller: SerieBundle:Default:mod }
    requirements:
        id:  "\d+"

serie_detail:
    path:     /serie/{id}
    defaults: { _controller: SerieBundle:Default:detail }
    requirements:
        id:  "\d+"

serie_list:
    path:     /list/
    defaults: { _controller: SerieBundle:Default:list }

serie_search:
    path:     /search/{lkMethod}={lkValue}
    defaults: { _controller: SerieBundle:Default:search, lkValue: '' }
    requirements:
            lookingFor:  "series|actors|users"

serie_list_catagory:
    path:     /list/{id}
    defaults: { _controller: SerieBundle:Default:listCategory }
    requirements:
            id:  "\d+"

episode_detail:
    path:     /serie/{idSerie}/episode/{idEpisode}
    defaults: { _controller: SerieBundle:Default:detailEpisode }
    requirements:
        idSerie:  "\d+"
        idEpisode: "\d+"

serie_add:
    path:     /comment/add/{id}
    defaults: { _controller: SerieBundle:Default:add }
    requirements:
            id:  "\d+"

serie_actors:
    path:     /list/actors
    defaults: { _controller: SerieBundle:Default:listActors }