#user_homepage:
#    path:     /
#    defaults: { _controller: UserBundle:Security:index }

user_login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

user_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Security:logout }