#user_homepage:
#    path:     /
#    defaults: { _controller: UserBundle:Security:index }

user_login:
    path:     /login
    defaults: { _controller: UserBundle:Security:login }

user_logout:
    path:     /logout
    defaults: { _controller: UserBundle:Security:logout }

user_register:
    path:     /register
    defaults: { _controller: UserBundle:Registration:register }

user_profile:
    path:     /profile/{id}
    defaults: { _controller: UserBundle:Profile:show }
    requirements:
        id:  "\d+"
