like:
    path: /like/{id}
    defaults: {_controller: ToolBundle:Default:like }
    requirements:
        id: "\d+"

dislike:
    path: /like/{id}
    defaults: {_controller: ToolBundle:Default:dislike }
    requirements:
        id: "\d+"

score:
    path: /score/{id}/{note}
    defaults: {_controller: ToolBundle:Default:score }
    requirements:
        id: "\d+"
        note: "[1-5]"